CREATE TABLE IF NOT EXISTS TODO (
	id BIGINT GENERATED BY DEFAULT AS IDENTITY,
	task varchar(255) not null
);


create sequence todo_sequence start with 1 increment by 1;

insert into TODO (task) values ('Show how hibernate works');
insert into TODO (task) values ('Show how flyway works');